### ISSUE TITLE
Required option not working as expected

### ISSUE THREAD

**Issue by Codpoe** [cacjs/cac#107]
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

## Expected

```
cli
  .command('create [dir]')
  .option('--template <template>')
```

If I didn't pass the `template`, it should throw an error like：`option "template" value is missing`.

## Actual

No error, continue to execute

## Possible Solutions

`Command.ts` - `checkOptionValue`

## Info

- CAC version: 6.7.2

**Comment by 0x009922** [comment]
@Codpoe, why this issue is closed? I've faced with this problem too.

**Comment by Codpoe** [comment]
@0x009922 In the case I mentioned above, if my usage is:
```
create --template
```
It will throw an error. That is, if you write a **argument name** but don’t include a **value**, it will report an error.
And I think it was the right thing to do, so I closed the issue.

But on the whole, I think it would be better if `cac` could support something like `requiredOption` in `commander`. Maybe like this:
```
cli
  .command('create [dir]')
  .option('--template <template>', { required: true });
```

**Comment by 0x009922** [comment]
@Codpoe, I agree with you about `requiredOption`, it look's like really missing feature.

**Comment by aleclarson** [comment]
https://www.npmjs.com/package/@cac/required-option
