### ISSUE TITLE
Show root help for wildcard command

### ISSUE THREAD

**Issue by egoist** [cacjs/cac#20]
If you have a wildcard command like:

```js
cli.option('foo', desc)

const wildcard = cli.command('*', desc, handler)
wildcard.option('bar', desc)
```

And when you run `cli.js --help` it currently prints message that includes `bar` instead of `foo`. Which means you can never see root help!

We should actually make wildcard command show root help instead of command help, and force user to add an alias name to the wildcard command so that it's possible to get the help for your wildcard command too:

```js
cli.option('foo', desc)

const wildcard = cli.command('*', { alias: 'hi', desc }, handler)
wildcard.option('bar', desc)
```

In this case, run `cli.js --help` for root help, run `cli.js hi --help` for the help of your wildcard command.

**Comment by niftylettuce** [comment]
It looks like this was a breaking change, can you please document and/or put an example in the examples folder how to use wildcard option?

**Comment by egoist** [comment]
@niftylettuce that's called default commmand now https://github.com/cacjs/cac/blob/master/README.md#default-command

**Comment by niftylettuce** [comment]
@egoist thank you
