### ISSUE TITLE
Alias resolving appears to be broken

### ISSUE THREAD

**Issue by unconfident** [cacjs/cac#21]
If multi-character option alias ends with a character that is used as a single-character alias for another option args will be parsed incorrectly and the value will be assigned to that single-character option

Example: 

```js
const cac = require('cac');

const cli = cac({ bin: 'package-name' });

cli
  .command('*', { desc: 'Example' }, (input, opts) => {
    console.log(opts);
  })
  .option('option', {
    alias: 'o', type: 'string',
    default: 'option-default',
  })
  .option('anotheroption', {
    alias: 'ao', type: 'string',
    default: 'another-option-default',
  });

cli.parse();
```

If I then execute it I get:

```
$ node ./cli.js -ao provided-ao-value
{ version: false,
  v: false,
  help: false,
  h: false,
  a: true,
  o: 'provided-ao-value',
  option: 'provided-ao-value',
  anotheroption: 'another-option-default',
  ao: 'another-option-default',
  '--': [] }
```

expected

```
{ ...
  o: 'option-default',
  option: 'option-default',
  anotheroption: 'provided-ao-value',
  ao: 'provided-ao-value',
  '--': [] }
```

I would have assumed that multi-character aliases aren't supported, but [`poi` has some](https://github.com/egoist/poi/blob/76387054606da38a4f107a0787f2c17a9d6ebd7c/packages/poi/bin/main.js#L88-L91), so it looks like it should be.

Cac version 4.4.4

**Comment by egoist** [comment]
`-ao` is actually a shorthand of `-a -o`, you should use `--ao`

**Comment by unconfident** [comment]
Oh. Well, sorry then, I guess it works as intented. Thanks for clarifying that
