### ISSUE TITLE
How to array

### ISSUE THREAD

**Issue by hipstersmoothie** [cacjs/cac#24]
There are no examples on how to supply an array. Have tried a bunch of different ways.

```
command --array ["/","/about"]                    
```

**Comment by hipstersmoothie** [comment]
It worked! I feel this should be added to docs as it is not obvious that this is the behavior. Also:

```
command --array /
```

Throws and error that array is not array

But if I do two array args everything works:

```
command --array / --array /about
```

So it seems you cannot pass an array with one element to the CLI.

**Comment by egoist** [comment]
maybe we should allow using `type: 'array'` to convert it to an array.
