### ISSUE TITLE
Allow options to be used before commands

### ISSUE THREAD

**Issue by balupton** [cacjs/cac#25]
I am looking to implement cac into DocPad. However, I need to be able to specify options before or after commands.

Here is an example source file:

``` javascript
'use strict'

const cli = require('cac')()

cli.option('opt', {
	type: 'boolean',
	desc: 'a boolean option'
})

cli.command('cmd', {
	desc: 'a command'
}, function (input, flags) {
	console.log('cmd:', { input, flags })
})

cli.command('*', {
	desc: 'show help'
}, function (input, flags) {
	cli.showHelp()
})

cli.parse()
```

And here is its output:

```
> node cac.js --opt cmd

  cac.js 6.81.0

  project description

  USAGE

    cac.js <command> [options]

  COMMANDS

    cmd  a command
    *    show help

  GLOBAL OPTIONS

    -v, --version  Display version                     [Type: boolean]
    -h, --help     Display help (You're already here)  [Type: boolean]
    --opt          a boolean option                    [Type: boolean]
```

```
> node cac.js cmd --opt
cmd: { input: [],
  flags:
   { version: false,
     v: false,
     help: false,
     h: false,
     opt: true,
     '--': [] } }
```

The former output should behave the same as the latter output.

**Comment by balupton** [comment]
Ok figured out a workaround.

**Comment by egoist** [comment]
If they work in the same way then `bin --opt cmd` would be very confusing, you can't tell if it is a sub command unless you already know `--opt`'s type is boolean

BTW Can you list some software that actually allow this? In `git` you can do `git log --log-size` but `git --log-size log` doesn't work.

**Comment by balupton** [comment]
> unless you already know --opt's type is boolean

Which if information cac does know

> BTW Can you list some software that actually allow this?

npm

**Comment by balupton** [comment]
Going to close this for now, as I have no need for this feature anymore, as the workaround I came up with earlier is working fine for my use case.

It would be nice to see, as other CLI apps do use this, but it is suitable edge case that has workarounds that it isn't important.

**Comment by egoist** [comment]
So, I think CAC will support this in 6.0 🤔 Working on it!

**Comment by jgoux** [comment]
Hello, I encountered this issue as well.

A good use case is also shebang! I'm working on making `vite-node` compatible with shebang and I realized that :
`#!/usr/bin/env vite-node --script-mode` was not giving me what I expect.

When calling the script with something like: `snaplet-scripts dev`, process.argv will be:
```
[
    '/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node',
    '/Users/jgoux/Documents/code/snaplet-labs/node_modules/.bin/vite-node',
    '--script-mode',
    '/Users/jgoux/Documents/code/snaplet-labs/apps/api/node_modules/.bin/snaplet-scripts',
    'dev'
  ]
```

And cac will interpret it like this:
```
files: [ 'dev' ],
  options: {
    '--': [],
    scriptMode: '/Users/jgoux/Documents/code/snaplet-labs/apps/api/node_modules/.bin/snaplet-scripts'
  }
```

Ideally I would expect:
```
files: [ '/Users/jgoux/Documents/code/snaplet-labs/apps/api/node_modules/.bin/snaplet-scripts', 'dev' ],
  options: {
    '--': [],
    scriptMode: true
  }
```
