### ISSUE TITLE
Cannot show help message with `-h` under command.

### ISSUE THREAD

**Issue by ulivz** [cacjs/cac#32]
## Example

```bash
vuepress dev --help   # works and show help
vuepress dev -h        # run dev's handler
```

**Comment by egoist** [comment]
Works for me 🤔

**Comment by egoist** [comment]
oops it doesn't

**Comment by egoist** [comment]
<img width="394" alt="2018-11-28 12 39 39" src="https://user-images.githubusercontent.com/8784712/49096738-28ee5100-f2a6-11e8-9b6f-c81cb112f7df.png">


You should remove `-h` below 

```
    .option('-h, --host <host>', 'use specified host (default: 0.0.0.0)')
```

since it conflicts with the help flag.

**Comment by ulivz** [comment]
Got it, Thanks~
