### ISSUE TITLE
Providing both an --option and a --no-option variant causes the option to always be boolean.

### ISSUE THREAD

**Issue by spiltcoffee** [cacjs/cac#34]
Providing both an --option and a --no-option variant causes the option to always be boolean.

This means even if --option takes in a [value] or <value>, since --no-option is defined, it will only ever be true or false, and specifying a value causes it to be interpreted as an argument instead.

Example repo: https://github.com/spiltcoffee/cac-no-example

**Comment by spiltcoffee** [comment]
That should be okay, because I think we do look at siteConfig.cache if --no-cache is used then?

**Comment by egoist** [comment]
@spiltcoffee well at least this is the same in commander.js

**Comment by ulivz** [comment]
Cool~ ❤️
