### ISSUE TITLE
coerce option is never run

### ISSUE THREAD

**Issue by bdistin** [cacjs/cac#39]
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

## Expected
The coerce option config to run/coerce the results to the returned options.

## Actual
The coerce option doesn't seem to run.

## Possible Solutions
It appears the coerce option is never run in cac source. cac should run the coerce option on options with a coerce option defined.

## Info

- CAC version: 6.3.9
- Reproduction link: https://repl.it/repls/CoordinatedWavyDisk

**Comment by egoist** [comment]
Thanks for reporting the issue, I just removed it from the docs since it's not necessary and we haven't implemented it, however we maybe add this feature in the future.
