### ISSUE TITLE
[Bug Report] Multiple words negated options

### ISSUE THREAD

**Issue by meteorlxy** [cacjs/cac#61]
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Steps to repro

```js
// test.js
const cli = require('cac')();

cli.option('--no-aaa-bbb').option('--no-ccc');

const parsed = cli.parse();

console.log(JSON.stringify(parsed, null, 2));
```

```sh
$ node test.js
{
  "args": [],
  "options": {
    "--": [],
    "aaa-bbb": true,
    "ccc": true
  }
}

$ node test.js --no-aaa-bbb
{
  "args": [],
  "options": {
    "--": [],
    "aaa-bbb": true,
    "ccc": true,
    "aaaBbb": false
  }
}

$ node test.js --no-ccc
{
  "args": [],
  "options": {
    "--": [],
    "aaa-bbb": true,
    "ccc": false
  }
}
```

The `"aaa-bbb": true` is always there.

## Info

- CAC version: 6.5.3

**Comment by egoist** [comment]
I updated the docs for this: https://github.com/cacjs/cac#dash-in-option-names

Maybe we should delete the `options['foo-bar']` to reduce confusion

**Comment by meteorlxy** [comment]
Well, the point is that:

- options without dash have default value `true`
- options with dash have default value `undefined`

They are inconsistent

**Comment by egoist** [comment]
I see, I'll fix it.
