### ISSUE TITLE
cac not working with Deno 1.0.0

### ISSUE THREAD

**Issue by BentoumiTech** [cacjs/cac#75]
## Issue Type

Deno recently removed the usage of `window.location.pathname` which now break the fix that was implemented in #70 

- [x] Bug Report

## Expected

`cac` working with Deno

## Actual

Rising an exception

## Possible Solutions

Replace `deno && typeof window !== 'undefined' && window.location.pathname` with `import.meta.url`

## Info

- CAC version: 6.5.8

**Comment by egoist** [comment]
I completely removed that since `import.meta.url` or the old `location.pathname`  is the filename of `cac/mod.js` rather than your program. Now just do `cac('my-program')` instead. I also fixed the types for Deno: https://github.com/cacjs/cac#with-deno

**Comment by BentoumiTech** [comment]
@egoist Thank you for the quick fix.

I've updated my code to work with your last upgrade and included the types but vscode with the deno extension is still complaining here: https://github.com/BentoumiTech/denox/blob/612a2e43f7f16ba53b08cd1c6cfedc8ebe7a6d89/denox.ts#L19

Do you have any idea on why this is reporting an error ?

Repo link: https://github.com/BentoumiTech/denox

**Comment by egoist** [comment]
Ah sorry I just realized this feature is not supported by the vscode plugin yet. denoland/vscode\_deno#21

**Comment by BentoumiTech** [comment]
@egoist No worries, thanks for your help :)
