### ISSUE TITLE
Native ESM (Node 13+) Support

### ISSUE THREAD

**Issue by talentlessguy** [cacjs/cac#85]
## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Other

## Expected

ESM support so we can do this:

```js
import cac from 'cac'

const cli = cac()

// ...
```

## Actual

No ESM support for Node.js

## Possible Solutions

Adding these fields to package.json

```json
"type": "module",
"module: "...",
"exports": {
    ".": {
      "import": "./dist/index.js",
      "require": "./dist/index.cjs"
    },
    "./package.json": "./package.json",
    "./": "./"
  }
```

Note that CJS will still work as before, here's an example of such module: https://github.com/talentlessguy/es-mime-types

Because this project already uses Rollup, it will be very easy to add a module target.

## Info

- CAC version: 6.15.3

if needed, I can make a pull request

**Comment by egoist** [comment]
Nice, I guess point `import` to `./mod.js` would just work then 👌
